# sections.yaml
sections:
  "D科棟":
    start:
      position:
        x: 50
        y: 11.7
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -1.0
        w: 0.0
    end:
      position:
        x: 30.4
        y: 11.8
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  "共通棟-ロボコン部前":
    start:
      position:
        x: 30.3
        y: 11.9
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.707
        w: 0.707
    end:
      position:
        x: 30.5
        y: 64.5
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.707
        w: 0.707
  "共通棟-共通3前":
    start:
      position:
        x: 30.6
        y: 64.5
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    end:
      position:
        x: 68.2
        y: 64.4
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 1.0
        w: 0.0
  "E科棟":
    start:
      position:
        x: 68.3
        y: 63.9
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.707
        w: 0.707
    end:
      position:
        x: 68.2
        y: 25.6
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.707
        w: 0.707
